### ISSUE TITLE
Error: Failed to create file: Access is denied. (os error 5)

### ISSUE THREAD

**Issue by joshdbennett** [scarvalhojr/aoc-cli#2]
(base) PS C:\DATA\Git\azuredevops\adventofcode> aoc download --year 2015 --day 1 --file C:\Users\jbennett010\aoc\2015\1\input
Loaded session cookie from "C:\Users\jbennett010\.adventofcode.session".
Downloading input for day 1, 2015...
Saving puzzle input to "C:\Users\jbennett010\aoc\2015\1\input"...
Error: Failed to create file: Access is denied. (os error 5)

**Comment by scarvalhojr** [comment]
Check that the directory you're trying to write to exists and that you you have write permissions on it.

You can check if this works:

```
echo hello > C:\Users\jbennett010\aoc\2015\1\input
```

**Comment by scarvalhojr** [comment]
Closing this for now. Let me know if you're still having issues.
