### ISSUE TITLE
Support output in Markdown format (as an alternative to plain text output)

### ISSUE THREAD

**Issue by hashworks** [scarvalhojr/aoc-cli#4]
The example of 2021 Day 9 is not displayed properly:
```
Smoke flows to the lowest point of the area it's in. For example, consider the following heightmap:

`2*1*9994321*0*
3987894921
98*5*6789892
8767896789
989996*5*678
`
```

Piping this into `mdcat` will display it wrong:
![bad-example](https://fb.hash.works/5vyNe1/)

This should be a code block (```) instead of single line monospace:
![better-example](https://fb.hash.works/4OR9mR/)

The cursive numbers are a problem as well, but I'm not sure if there is a good solution for that.

**Comment by scarvalhojr** [comment]
Hi @hashworks, the output is not Markdown. It's just a simple HTML conversion to text for human consumption in the terminal (using https://crates.io/crates/html2text).

It wouldn't be hard to add support for Markdown output so I'll leave this issue open in case anyone wants to implement it.
