### ISSUE TITLE
Support `.config` and environment variable for session

### ISSUE THREAD

**Issue by ModProg** [scarvalhojr/aoc-cli#8]
For config dir, you could use: https://docs.rs/dirs/4.0.0/dirs/fn.config_dir.html

And for environment variable, I'd imagine something like `ADVENT_OF_CODE_SESSION`.

I'd be willing to implement this my self.

**Comment by ModProg** [comment]
The `.config` would be on top of the current location to stay backward compatible.

**Comment by scarvalhojr** [comment]
That's a great idea, please feel free to submit a PR. We could have config_dir as default and if not found revert to home dir.

Not so sure about the env var as that could be a little confusing for users (which one takes precedence?) and possibly less safe (if exported as clear text), but happy to consider it too.

I'd suggest two separate PRs to make it easier to review.

**Comment by ModProg** [comment]
The environment variable was actually meant to enable one to use tools that support storing env variables on the keychain.

**Comment by scarvalhojr** [comment]
That's a good point! My comment about it being less safe was about users doing `export SESSION=xyz` on the command line and the cookie staying in the shell history. Not a major problem, of course. Having it in the keychain would be neat!

**Comment by zneix** [comment]
To extend on what OP requests, I'd suggest fully following XDG specification instead of hardcoding support for `~/.config`. While the config directory is usually placed at `~/.config` and that's the default location, it can be changed to some other location with `XDG_CONFIG_HOME` environment variable. For reference, see: https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

**Comment by ModProg** [comment]
> To extend on what OP requests, I'd suggest fully following XDG specification instead of hardcoding support for `~/.config`. While the config directory is usually placed at `~/.config` and that's the default location, it can be changed to some other location with `XDG_CONFIG_HOME` environment variable. For reference, see: https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

already did so
